# Generated by Django 5.1.5 on 2025-01-17 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catastro_inmuebles_01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='receptor_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptor_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tramite',
            name='resultor_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultor_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
