# Generated by Django 5.1.5 on 2025-01-21 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catastro_inmuebles_01', '0003_tramite_lider_proyecto_tramite_sub_lider_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='resultor_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultor_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='lider_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='resultor_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultor_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='sub_lider_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_lider_proyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('recepcionista', 'Recepcionista'), ('inspector', 'Inspector'), ('resultor', 'Resultor'), ('lider_proyecto', 'Líder de Proyecto'), ('sub_lider_proyecto', 'Sub Líder de Proyecto'), ('resultor_proyecto', 'Resultor de Proyecto')], default='recepcionista', max_length=20),
        ),
    ]
